### ISSUE TITLE
Feedly does not recognize feed

### ISSUE THREAD

**Issue by tkrotoff** [tkrotoff/osteo15.com#17]
2014/03/12:

> Hi,
> # Short version
> - How do I force Feedly to reset its internal cache for https://osteo15.com/blog.atom? (http://feedly.com/i/subscription/feed/https://osteo15.com/blog.atom)
> - Do you confirm that both RSS and Atom work with HTTPS SNI? (1)
> - Are https://osteo15.com/feed.xml and https://osteo15.com/blog.atom OK? (2)
> # Long version
> 
> I have a Jekyll site (https://github.com/tkrotoff/osteo15.com) hosted on Amazon S3 using exclusively HTTPS (no HTTP version) with SNI (http://en.wikipedia.org/wiki/Server_Name_Indication).
> When I try the original RSS feed provided with Jekyll template (http://feedly.com/i/subscription/feed/https://osteo15.com/feed.xml), Feedly does not show anything.
> 
> In the absence of detailed feedback from Feedly, I tried to debug this:
> 
> I took the feed from https://github.com/blog (https://github.com/blog.atom) as I known they use exclusively HTTPS with SNI (1) and it works on Feedly.
> 
> I ended up with https://osteo15.com/blog.atom being a copy-pasted version of https://github.com/blog.atom and Feedly showing the posts => good!
> I've concluded that Feedly might have some problems with my original RSS feed content (https://osteo15.com/feed.xml) and probably not with HTTPS/SNI.
> 
> I've updated https://osteo15.com/blog.atom in order to display my real content and not the one from GitHub blog.
> And here I'm stuck: Feedly displays some items from my real content and items from https://github.com/blog.atom.
> 
> What would be really nice is to have some tools for developers to debug a RSS/Atom feed and give more feedback on http://feedly.com/i/subscription/feed/* when something is wrong.
> 
> Regards,
> 
> (1) You know a website uses exclusively HTTPS with SNI when IE8 under Windows XP complains "Internet Explorer cannot display the webpage" since IE under XP does not support SNI.
> VMs with IE8/XP are available at https://www.modern.ie/en-us/virtualization-tools#downloads
> 
> (2) Both https://osteo15.com/feed.xml and https://osteo15.com/blog.atom are properly displayed natively in Firefox and old Opera (version 12). I've also checked with http://validator.w3.org/feed/#validate_by_input and they are both valid.
> 
> Feedly Pro (Support) wrote:
> 
> > We don't provide tools for validate RSS/Atom but you can find some on the internet, like this one http://validator.w3.org/feed/
> 
> Yeah I know about http://validator.w3.org/feed/ since I mentioned it in my email...
> As for the tools, as said, would be nice to at least give some feedback on http://feedly.com/i/subscription/feed/*
> 
> > As you can see you have encoding issue in your feed https://osteo15.com/feed.xml that's why our parser fail.
> 
> ? I don't see any encoding issue using http://validator.w3.org/feed/, nor with Firefox and Opera 12, see screenshots.
> I've also checked with several XML validators (http://www.xmlvalidation.com/, http://validator.w3.org/check, http://xmlgrid.net/validator.html) => no errors.
> Is your parser open source so I can check myself what's going on?
> 
> > To delete an article, the trick is to leave the article in your feed, but update the title/content with [removed] or something like that. Then at least the content will be removed, even if the article remains. There is no way to "delete" article automatically via rss.
> 
> How long data stays in your internal cache?

Reply:

> Feedly Pro (Support) wrote:
> 
> > The feed have been exceptionally cleared : http://feedly.com/i/subscription/feed/https://osteo15.com/blog.atom
> 
> Thanks!
> 
> > About encoding when i test in chrome the UTF-8 look broken for me : <title>Petit dÃ©jeuner et cÃ©rÃ©ales</title>
> 
> Encoding problems should not impact parsing, the only impact is for the user: garbage text displayed. And I'm not even sure Chrome is right since the garbage text is only from DevTools/Network/Response, the local file on my HD is fine (UTF-8 and declared as such in the XML), Firefox and Opera don't have any problem.
> It seems Feedly parser does not like encoding problems unlike others.
> 
> > The reason why https://osteo15.com/blog.atom work and not https://osteo15.com/feed.xml is because the feed.xml have gzip enabled so if you disable it'll work also.
> 
> You are right, it works without gzip \o/ (even after renaming feed.xml to https://osteo15.com/blog.rss in order to bypass Feedly cache).
> Your HTTP client does not support gzip !?
> 
> The only way to bypass your cache is to create a new Atom/RSS file, https://osteo15.com/blog.atom does not work, https://osteo15.com/blog3.atom does, both are identical.
> 
> So if one day the original feed is fucked for whatever reason (encoding problem for example), it stays like that even if fixed upstream => quite dangerous... And what if the original feed has been removed? (obsolete, replaced or contained confidential data)
> 
> I thus see several improvements that you can make:
> - Unit test with wrong encoding
> - Update HTTP client to allow gzip
> - Give feedback like "HTTP 404 File Not Found", "Could not parse file: link_to_file_as_seen_by_feedly", "Last Feedly update: 2015-03-12 22:25"...
> - Allow for cache reset with a parameter: http://feedly.com/i/subscription/feed/https://osteo15.com/blog.atom?cache_reset=1
> - Documentation for all this
> 
> This way we would not have wasted time with this discussion :)

The main problem was about gzipping feed.xml: Feedly does not support gzip and HTTPS.

As for the cache, there is no way to reset it and I don't know how long they cache things. To trick the cache, the only way is to create a new feed (ex: blog2.atom, blog3.atom, blog4.atom...).

I've renamed feed.xml to blog.rss while keeping blog.atom. blog.rss now seems to work.

**Comment by tkrotoff** [comment]
See commit 1d5e584b0494d5c4a45e0ca5d31adfc447585da1

**Comment by RyanGittins** [comment]
Hey, thanks for taking the time to document all of this.  It saved me a *tremendous* amount of hassle while building [siftrss](https://siftrss.com).  It's been almost two years and Feedly still doesn't seem to support gzip!
